### ISSUE TITLE
[WARN] [1589625192.191877, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.

### ISSUE THREAD

**Issue by dilipdhapse** [olinrobotics/tractor_sim#21]
![image](https://user-images.githubusercontent.com/33243624/82117651-119f6e00-978f-11ea-94c7-a40a0a78b156.png)

**Comment by AmyPhung** [comment]
#22 This happens when the controller spawner node is started before gazebo fully loads. For now, for the controller spawner node, `respawn="true"`. The warning is still there, but it should work now
